### ISSUE TITLE
[Son Son]Error: Illegal addressing mode

### ISSUE THREAD

**Issue by gb-2312** [cyneprepou4uk/NES-Games-Disassembly#10]
Hi friend,

Today I was trying to check these projects, and found that the game `Son Son` has an error message during compilation:

`bank_FF.asm(7676): Error: Illegal addressing mode`

I located the specific error in the file (line 7676 of the code), and found a problem:
```c
C - - - - - 0x003031 00:B021: 85 87     STA     ; screen pos hi
```

It should be:
```c
C - - - - - 0x003031 00:B021: 85 87     STA ram_0087    ; screen pos hi
```

After modify and save, it successfully compiles and runs correctly.
Thanks

**Comment by cyneprepou4uk** [comment]
fixed 347d5e51724abc22b67035f2e2b6043e9393493a
